### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found

### ISSUE THREAD

**Issue by pavelsollo** [TiagoDanin/StoreOfBot#44]
the bot start shows an error in the console and does not start, what might be the problem

(node:17496) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found
    at /root/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TiagoDanin** [comment]
Did you create the .env?
